
.PHONY = clean

clean:
	@cd ./hello && make clean 
	@cd ./spmp0 && make clean 
	@cd ./smpu0 && make clean 
	@cd ./smpu1 && make clean 
	@cd ./smpu2 && make clean 
	@cd ./smpu3 && make clean 
	@cd ./smpu4 && make clean 
	@cd ./trap0 && make clean 
	@cd ./trap1 && make clean 
	@cd ./trap2 && make clean 
	@cd ./trap3 && make clean 
	@cd ./trap4 && make clean 
